name: Run Gradle Build
on: [ push ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        name: Setup Java
        with:
          distribution: temurin
          java-version: 17
      - name: Build
        run: ./gradlew build
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
            repo_token: '${{ secrets.GITHUB_TOKEN }}'
            automatic_release_tag: "1.8.9"
            prerelease: true
            title: "1.8.9"
            files: |
              ./build/libs/*.jar
